version: '2'

services:
  meilisearch:
    container_name: meilisearch
    image: getmeili/meilisearch:v0.26.0
    ports:
      - 7700:7700
    volumes:
      - ./data/data.ms:/data.ms
    env_file:
      - server/.env
  chat-archiver:
    build: .
    ports:
      - 8080:8080
    env_file:
      - server/.env